name: Build Python Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build application with PyInstaller
        run: |
          pyinstaller --onedir --console --add-data "model:model" --add-data "utils:utils" --add-data "libs/mediapipe:mediapipe" --add-data "libs/protobuf:protobuf" app.py

      - name: Create ZIP of output
        run: |
          cd dist
          zip -r ../hand-gesture-v${{ github.run_number }}.zip * 

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZIP to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          files: hand-gesture-v${{ github.run_number }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set versioning
        run: |
          echo "VERSION=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV
